dist: trusty
services:
- docker
before_script:
- docker pull drugilsberg/rdkit-ubuntu:latest
- docker build -f .travis/Dockerfile -t predictor .
script:
- docker run -it predictor python3 -c "import paccmann_predictor"
- docker run -it predictor python3 examples/train_paccmann.py -h
notifications:
  slack:
    secure: YnxwDvXXN2UCoTWG+dgfvOMjrgCt9Gh2D9Ll1Gv3eNHu9wT1YRqM3WP8yW8LVccmTdu1pW/aRPiwF9K5/bBl5dCHNOj//dNWxXCixrrJAPkyZOSgVHERl/NQuiJDpnQE/kdMXqhg/SV0fuv7sDasNsg2APjw4DlrfJOaJCVdQzfQ9DQbu3lf3ANSI5aaJX5gcqpeTIhSWoEdjzX3uAia6AwSEuBr5jKl4gpFNmAwFgIaIAV8rL1KZSPHn9ajmldxxOfOI1tdgQEXy/kd2iadfqjzy/MSRjIgOqCAPKdjAa925sor/SrsHEBkTSLAYw3eVROftwq4grVGDm0Gltanld6NYz4Lt2wyCPxe0vaCVsSug4owQjvzh5HeWhWU+HzZBXLiHPygQ7YN0cpVKNzVkMgJsGEzIzcPS5UyyO2E2nQ4xfVsJHiiox6fydHmO0zBjwTshtaDFvLpgQ1G/+yReelFrqIKTsnebA9yPIcw63c6Hc28T+mUnWAXA0ekkB2E8IyroFTI8lAfKjwz5sLzMFwugkPrYfO07hzCGwsX47fGUEgu6hTwVmqcx0Eqv7OUmELPc1cI/ECSB90BMKqX/yrT26l5lWcJ8VfklgmCLnhHATfff5mXCAjgkHBBplo+VGz/QXcJ+LeTwaplyi66S5yWINPXzfyw/N9tcikXzAU=
    on_success: always
    on_failure: always
